# -*- coding: utf-8 -*-
"""
Generate the achievement cards csv - kind of a pain in straight text
due to the number of grid locregions.

Created on Fri Feb 18 12:00:06 2022

@author: phill
"""

import sys

columns = ["players","stage","star","locregion","locresource","name","g11","g12","g13","g14","g21",
            "g22","g23","g24","g31","g32","g33","g34","g41","g42","g43","g44","f11","f12",
            "f13","f14","f21","f22","f23","f24","f31","f32","f33","f34","f41","f42","f43","f44","reward"]
    
card_dict_1p = {
    '1': {
        'Metals and Guilds': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f22': 'YTxxONEYT',
            'f33': 'YTxxONEYT',
            'f44': 'xxONE',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Games Without Frontiers': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'YTxxTWOYT',
            'f21': 'MTxxEMPIREMT',
            'f22': 'xxPSYCHE',
            'f23': 'GTxxEMPIREGT',
            'f32': 'OTxxEMPIREOT',
            'f42': 'xxTWO',
            'reward': 'MMxxESPIONAGEMM'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f11': 'BTxxREDBANKBT',
            'f21': 'xxPSYCHE',
            'f31': 'OTxxPSYCHEOT',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'BLxxSORCERYBL'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'GTxxTHREEGT',
            'f12': 'xxFOUR',
            'f21': 'xxTHREE',
            'f23': 'xxFOUR',
            'f24': 'MTxxFOURMT',
            'f32': 'xxTHREE',
            'reward': 'LLxxDIPLOMACYLL'},
        'On Two Fronts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxFIVE',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'Bread and Circuses': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f13': '>',
            'f23': 'GTxxBODYGT',
            'f24': '>',
            'f34': '>',
            'reward': 'YYxxSTABILITYYY'},
        'Elegant Accoutrements': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'LExxFSQUARELE',
            'f21': 'xxFOUR',
            'reward': 'BBxxESPIONAGEBB'},
        'Along the Wall': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'MExxFSQUAREME',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f22': 'GTxxEMPIREGT',
            'f23': '>',
            'f33': '>',
            'reward': 'BBxxMILITARYBB'},
        'Tough Choices': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'YExxFSQUAREYE',
            'f12': 'xxTHREE',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'reward': 'BBxxSTABILITYBB'},
        'Friend in Every Port': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'LTxxFOURLT',
            'f12': 'YTxxFOURYT',
            'f13': 'MTxxFOURMT',
            'reward': 'BBxxDIPLOMACYBB'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxSIX',
            'f21': 'BTxxBODYBT',
            'f22': 'xxSIX',
            'f23': 'BTxxPSYCHEBT',
            'f32': 'xxSIX',
            'reward': 'BBxxSORCERYBB'},
        'Cautious Progress': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '<',
            'f33': '<',
            'reward': 'BBxxTECHNOLOGYBB'},
        'Expert Training': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f21': 'xxTWO',
            'f22': 'xxTHREE',
            'f32': 'xxFOUR',
            'f33': 'xxFIVE',
            'reward': 'xxCOMMITMENT'},
        'Personal Ups and Downs': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'YTxxTHREEYT',
            'f21': '<',
            'f22': '>',
            'f32': '<',
            'f33': '>',
            'reward': 'xxCOMMITMENT'},
        'Quick Wins': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': '=',
            'f31': '=',
            'reward': 'xxCOMMITMENT'},
        },
    '2': {
        'Local Investments': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'YExxFSQUAREYE', 
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'reward': 'OOxxTECHNOLOGYOO YYxxSTABILITYYY'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'reward': 'YYxxSTABILITYYY BBxxSTABILITYBB'}, 
        'Military Secrets': {
            'locregion': 'xxSETTLED', 
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BTxxSIXBT',
            'f33': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG BBxxMILITARYBB'},
        'Milk and Honey': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxFOUR',
            'f13': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL BLxxSORCERYBL'},
        'Guidance from Crescent Hold': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OTxxONEOT',
            'f22': 'OTxxTWOOT',
            'f31': 'xxSETTLED',
            'reward': 'MMxxESPIONAGEMM BBxxESPIONAGEBB'},
        'Rites of Winter': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'YTxxREDBANKYT',
            'f22': 'GTxxBODYGT',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxSIX',
            'reward': 'LLxxDIPLOMACYLL BBxxDIPLOMACYBB'},
        'Marching Orders': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'YYxxFSQUAREYY',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxSETTLED',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f23': 'LTxxSETTLEDLT',
            'f32': 'MTxxEMPIREMT',
            'f33': '=',
            'reward': 'GGxxMILITARYGG MMxxESPIONAGEMM'},
        'Wards Against the Deathless': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxBODY',
            'f21': 'xxPSYCHE',
            'f22': 'BTxxSIXBT',
            'f23': 'xxBODY',
            'f32': 'xxPSYCHE',
            'reward': 'BLxxSORCERYBL BBxxSORCERYBB'},
        'Empyrean Wilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': '>',
            'f23': '>',
            'f22': 'BTxxREDBANKBT',
            'f33': 'LTxxSETTLEDLT',
            'reward': 'OOxxTECHNOLOGYOO BBxxTECHNOLOGYBB'},
        'Unshakable Faith': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'BExxFSQUAREBE',
            'f11': 'xxSIX',
            'reward': 'xxCOMMITMENT xxCOMMITMENT'}
        },
    '3': {
        'Keeper of Natural Lore': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxSIX',
            'f21': 'xxSIX',
            'f31': 'xxSIX',
            'reward': 'BLxxSORCERYBL BLxxSORCERYBL'},
        'Speaker for Red Bank': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f21': 'xxFIVE',
            'f31': 'xxFIVE',
            'reward': 'YYxxSTABILITYYY YYxxSTABILITYYY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f21': 'xxONE',
            'f31': 'xxONE',
            'reward': 'OOxxTECHNOLOGYOO OOxxTECHNOLOGYOO'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxTHREE',
            'f21': 'xxTHREE',
            'f31': 'xxTHREE',
            'reward': 'GGxxMILITARYGG GGxxMILITARYGG'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxFOUR',
            'f21': 'xxFOUR',
            'f31': 'xxFOUR',
            'reward': 'LLxxDIPLOMACYLL LLxxDIPLOMACYLL'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxTWO',
            'f21': 'xxTWO',
            'f31': 'xxTWO',
            'reward': 'MMxxESPIONAGEMM MMxxESPIONAGEMM'},
        }
    }

card_dict_2p = {
    '1': {
        'Right Tool for the Job': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxTWO',
            'f13': 'xxTHREE',
            'f21': 'YYxxONEYY',
            'f23': 'YYxxSIXYY',
            'f24': 'xxFOUR',
            'f32': 'LLxxONELL',
            'f34': 'xxFIVE',
            'f43': 'BBxxONEBB',
            'f44': 'xxSIX',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Empire Waning': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'GGxxFSQUAREGG',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'OOxxFSQUAREOO',
            'g24': 'OOxxFSQUAREOO',
            'g31': 'YYxxFSQUAREYY',
            'g32': 'YYxxFSQUAREYY',
            'g34': 'GGxxFSQUAREGG',
            'g42': 'GGxxFSQUAREGG',
            'g43': 'OOxxFSQUAREOO',
            'g44': 'WExxFSQUAREWE',
            'f11': 'OTxxSIXOT',
            'f12': '<',
            'f21': '<',
            'f23': '<',
            'f32': '<',
            'f34': '<',
            'f43': '<',
            'f44': 'xxONE',
            'reward': 'MMxxESPIONAGEMM'},
        'At What Price?': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'OOxxFSQUAREOO',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'xxBODY',
            'f22': 'LTxxSIXLT',
            'f23': 'xxPSYCHE',
            'f33': 'MTxxSIXMT',
            'f34': 'xxBODY',
            'f41': 'xxREDBANK',
            'f43': 'xxPSYCHE',
            'reward': 'BLxxSORCERYBL'},
        'Power Behind the Throne': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'BTxxONEBT',
            'f12': 'GTxxTWOGT',
            'f13': 'OTxxTHREEOT',
            'f24': 'OTxxTWOOT',
            'f23': 'MTxxTHREEMT',
            'f34': 'GTxxFOURGT',
            'f44': 'BTxxONEBT',
            'reward': 'LLxxDIPLOMACYLL'},
        'Hopeless Odds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'OTxxEMPIREOT',
            'f21': 'xxREDBANK',
            'f31': 'xxSETTLED',
            'f32': 'BTxxBODYBT',
            'f42': 'MTxxEMPIREMT',
            'f43': 'xxREDBANK',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'No Margin for Error': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WExxFSQUAREWE',
            'f11': 'LTxxTHREELT',
            'f12': 'xxSETTLED',
            'f13': 'xxREDBANK',
            'f21': 'GTxxTHREEGT',
            'f24': 'xxEMPIRE',
            'f34': 'xxREDBANK',
            'f31': 'LTxxFOURLT',
            'f42': 'GTxxFIVEGT',
            'f43': 'xxFIVE',
            'reward': 'YYxxSTABILITYYY'},
        'Safehouses': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxEMPIRE',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f23': 'OTxxTHREEOT',
            'f32': 'OTxxFOUROT',
            'f33': '=',
            'f34': 'OTxxTWOOT',
            'f43': 'OTxxTHREEOT',
            'f44': '=',
            'reward': 'BBxxESPIONAGEBB'},
        'The Resistance': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g44': 'OOxxFSQUAREOO',
            'f11': 'YTxxREDBANKYT',
            'f22': '<',
            'f23': 'MTxxEMPIREMT',
            'f32': 'OTxxEMPIREOT',
            'f33': '<',
            'f44': '<',
            'reward': 'BBxxSTABILITYBB'},
        'Swordcraft': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxTHREE',
            'f12': 'OTxxTWOOT',
            'f21': 'OTxxONEOT',
            'f22': '>',
            'f23': 'GTxxTHREEGT',
            'f32': 'GTxxTWOGT',
            'f33': '>',
            'f34': 'GTxxFOURGT',
            'f43': 'OTxxFOUROT',
            'f44': '>',
            'reward': 'BBxxMILITARYBB'},
        'Hedge Magic': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'BSxxFSQUAREBS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'WExxFSQUAREWE',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'f12': '=',
            'f13': '=',
            'f14': '=',
            'f22': 'xxSETTLED',
            'f23': 'xxREDBANK',
            'reward': 'BBxxSORCERYBB'},
        'Mustering Aid': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',   
            'f11': 'BTxxTWOBT',
            'f21': 'YTxxREDBANKYT',
            'f23': 'LTxxTHREELT',
            'f32': 'LTxxFOURLT',
            'f34': 'LTxxSETTLEDLT',
            'f22': '>',
            'f33': '>',
            'f43': 'YTxxFIVEYT',
            'f44': '>',
            'reward': 'BBxxDIPLOMACYBB'},
        'Roads and Boats': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g43': 'YExxFSQUAREYE',
            'f11': 'OTxxTWOOT',
            'f12': 'xxREDBANK',
            'f22': 'OTxxTHREEOT',
            'f23': 'xxSETTLED',
            'f32': 'xxREDBANK',
            'f33': '=',
            'reward': 'BBxxTECHNOLOGYBB'},
        'Taverns and Tapestries': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'LSxxFSQUARELS',
            'g12': 'YYxxFSQUAREYY',
            'g13': 'LExxFSQUARELE',
            'g22': 'BBxxFSQUAREBB',
            'f12': '>',
            'f13': '>',
            'f22': '>',
            'reward': 'xxCOMMITMENT'},
        'Mutual Sacrifice': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f22': 'GTxxBODYGT',
            'f33': 'GTxxBODYGT',
            'reward': 'xxCOMMITMENT'},
        'Wisdom on the Road': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f21': 'xxEMPIRE',
            'f22': 'OTxxSETTLEDOT',
            'f32': 'OTxxEMPIREOT',
            'f33': 'xxSETTLED',
            'reward': 'xxCOMMITMENT'}
        },
    '2': {
        'Metals and Guilds': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f22': 'YTxxONEYT',
            'f33': 'YTxxONEYT',
            'f44': 'xxONE',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Games Without Frontiers': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'YTxxTWOYT',
            'f21': 'MTxxEMPIREMT',
            'f22': 'xxPSYCHE',
            'f23': 'GTxxEMPIREGT',
            'f32': 'OTxxEMPIREOT',
            'f42': 'xxTWO',
            'reward': 'MMxxESPIONAGEMM'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f11': 'BTxxREDBANKBT',
            'f21': 'xxPSYCHE',
            'f31': 'OTxxPSYCHEOT',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'BLxxSORCERYBL'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'GTxxTHREEGT',
            'f12': 'xxFOUR',
            'f21': 'xxTHREE',
            'f23': 'xxFOUR',
            'f24': 'MTxxFOURMT',
            'f32': 'xxTHREE',
            'reward': 'LLxxDIPLOMACYLL'},
        'On Two Fronts': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'MMxxFSQUAREMM',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxFIVE',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'Bread and Circuses': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g24': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f13': '>',
            'f24': '>',
            'reward': 'YYxxSTABILITYYY'},
        'Elegant Accoutrements': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'LExxFSQUARELE',
            'f21': 'xxFOUR',
            'reward': 'BBxxESPIONAGEBB'},
        'Along the Wall': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f22': 'GTxxEMPIREGT',
            'f23': '>',
            'f33': '>',
            'reward': 'BBxxMILITARYBB'},
        'Hard Choices': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'YExxFSQUAREYE',
            'f12': 'xxTHREE',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'reward': 'BBxxSTABILITYBB'},
        'Empyrean Wilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': '>',
            'f23': '>',
            'f22': 'BTxxREDBANKBT',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'BBxxTECHNOLOGYBB'},
        'Friend in Every Port': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'LTxxFOURLT',
            'f12': 'YTxxFOURYT',
            'f13': 'MTxxFOURMT',
            'reward': 'BBxxDIPLOMACYBB'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxSIX',
            'f21': 'BTxxBODYBT',
            'f22': 'xxSIX',
            'f23': 'BTxxPSYCHEBT',
            'f32': 'xxSIX',
            'reward': 'BBxxSORCERYBB'},
        'Expert Training': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f21': 'xxTWO',
            'f22': 'xxTHREE',
            'f32': 'xxFOUR',
            'f33': 'xxFIVE',
            'reward': 'xxCOMMITMENT'},
        'Aid the Fallen': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'GGxxFSQUAREGG',
            'g33': 'WExxFSQUAREWE',
            'f33': 'xxBODY',
            'reward': 'xxCOMMITMENT'},
        'Personal Ups and Downs': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'YTxxTHREEYT',
            'f21': '<',
            'f22': '>',
            'f32': '<',
            'f33': '>',
            'reward': 'xxCOMMITMENT'}
        },
    '3': {
        'Local Investments': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'WExxFSQUAREWE', 
            'f11': 'xxREDBANK',
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'reward': 'YYxxSTABILITYYY OOxxTECHNOLOGYOO'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxFOUR',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'reward': 'YYxxSTABILITYYY LLxxDIPLOMACYLL'},
        'Rites of Winter': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxSIX',
            'f12': 'xxREDBANK',
            'f22': 'BTxxBODYBT',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxSIX',
            'reward': 'YYxxSTABILITYYY BLxxSORCERYBL'},
        'Boars and Bandits': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxTHREE',
            'f21': 'xxFIVE',
            'f22': 'GTxxREDBANKGT',
            'f23': 'BTxxREDBANKBT',
            'reward': 'YYxxSTABILITYYY GGxxMILITARYGG'},
        'Traveling Minstrels': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxEMPIRE',
            'f22': '=',
            'f23': 'xxSETTLED',
            'f32': 'xxEMPIRE',
            'f33': '=',
            'reward': 'YYxxSTABILITYYY MMxxESPIONAGEMM'},
        'Milk and Honey': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxFOUR',
            'f13': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL OOxxTECHNOLOGYOO'},
        'Guidance from Afar': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OTxxONEOT',
            'f22': 'OTxxTWOOT',
            'f31': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL MMxxESPIONAGEMM'},
        'Cautious Progress': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '<',
            'f33': '<',
            'reward': 'LLxxDIPLOMACYLL GGxxMILITARYGG'},
        'Wards Against the Deathless': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxBODY',
            'f21': 'xxPSYCHE',
            'f22': 'BTxxSIXBT',
            'f23': 'xxBODY',
            'f32': 'xxPSYCHE',
            'reward': 'LLxxDIPLOMACYLL BLxxSORCERYBL'},
        'Military Secrets': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BTxxSIXBT',
            'f33': 'xxEMPIRE',
            'reward': 'MMxxESPIONAGEMM GGxxMILITARYGG'},
        'Cover Story': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxTWO',
            'f21': 'xxTWO',
            'f22': 'xxFOUR',
            'f31': 'YTxxFOURYT',
            'reward': 'MMxxESPIONAGEMM OOxxTECHNOLOGYOO'},
        'Ranging the Frontier': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'BExxFSQUAREBE',
            'f11': 'xxBODY',
            'reward': 'MMxxESPIONAGEMM BLxxSORCERYBL'},
        'Marching Orders': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f13': '=',
            'reward': 'GGxxMILITARYGG BLxxSORCERYBL'},
        'Research and Development': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'LLxxFSQUARELL',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxFOUR',
            'f13': 'xxSETTLED',
            'reward': 'GGxxMILITARYGG OOxxTECHNOLOGYOO'},
        'Experience Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': 'xxEMPIRE',
            'f31': 'xxSETTLED',
            'reward': 'OOxxTECHNOLOGYOO BLxxSORCERYBL'},
        },
    '4': {
        'Keeper of Natural Lore': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxSIX',
            'f12': 'xxSIX',
            'f13': 'xxSIX',
            'f24': 'xxSIX',
            'f34': 'xxSIX',
            'f44': 'xxSIX',
            'reward': 'BLxxSORCERYBL BLxxSORCERYBL'},
        'Speaker for Red Bank': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f12': 'xxFIVE',
            'f13': 'xxFIVE',
            'f24': 'xxFIVE',
            'f34': 'xxFIVE',
            'f44': 'xxFIVE',
            'reward': 'YYxxSTABILITYYY YYxxSTABILITYYY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxONE',
            'f13': 'xxONE',
            'f24': 'xxONE',
            'f34': 'xxONE',
            'f44': 'xxONE',
            'reward': 'OOxxTECHNOLOGYOO OOxxTECHNOLOGYOO'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxTHREE',
            'f12': 'xxTHREE',
            'f13': 'xxTHREE',
            'f24': 'xxTHREE',
            'f34': 'xxTHREE',
            'f44': 'xxTHREE',
            'reward': 'GGxxMILITARYGG GGxxMILITARYGG'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFOUR',
            'f12': 'xxFOUR',
            'f13': 'xxFOUR',
            'f24': 'xxFOUR',
            'f34': 'xxFOUR',
            'f44': 'xxFOUR',
            'reward': 'LLxxDIPLOMACYLL LLxxDIPLOMACYLL'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxTWO',
            'f12': 'xxTWO',
            'f13': 'xxTWO',
            'f24': 'xxTWO',
            'f34': 'xxTWO',
            'f44': 'xxTWO',
            'reward': 'MMxxESPIONAGEMM MMxxESPIONAGEMM'},
        }
    }

original_stdout = sys.stdout

with open ("D:\\Dropbox\\Ziapelta Games\\Games\\Six Winters\\six-winters\\csv\\achievement-cards-rskill.csv", "w") as csvfile:

    sys.stdout = csvfile

    # Print csv header
    for i in range(len(columns) -1):
        print(columns[i], ',', end='', sep='')
    print(columns[-1])
    
    print()
    
    for players, card_dict in zip([1,2], [card_dict_1p, card_dict_2p]):

        # Print rows
        for next_stage in card_dict.keys():
            for next_name in card_dict[next_stage].keys():
                for next_col in columns:
                    if next_col == 'players':
                        print('"', players, '",', end='', sep='')
                    elif next_col == 'stage':
                        print('"', next_stage, '",', end='', sep='')
                    elif next_col =='name':
                        print('"', next_name, '",', end='', sep='')
                    elif next_col == 'star':
                        print('"xxSTAR",', end='', sep='')
                    else:
                        if next_col in card_dict[next_stage][next_name].keys():
                            print('"', card_dict[next_stage][next_name][next_col], '",', end='', sep='')
                        else:
                            print('""', ',', end='', sep='')
                print()
            print()
        
    sys.stdout = original_stdout