# -*- coding: utf-8 -*-
"""
Generate the achievement cards csv - kind of a pain in straight text
due to the number of grid locregions.

Created on Fri Feb 18 12:00:06 2022

@author: phill
"""

import sys

columns = ["players","stage","star","locregion","locresource","name","g11","g12","g13","g14","g21",
            "g22","g23","g24","g31","g32","g33","g34","g41","g42","g43","g44","f11","f12",
            "f13","f14","f21","f22","f23","f24","f31","f32","f33","f34","f41","f42","f43","f44","reward"]
    
card_dict_1p = {
    '1': {
        'Metals and Guilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f22': 'YYxxONEYY',
            'f33': 'YYxxONEYY',
            'f44': 'xxWONE',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Games Without Frontiers': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g22': 'MMxxFSQUAREMM',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'YYxxTWOYY',
            'f42': 'xxWTWO',
            'reward': 'MMxxESPIONAGEMM'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f11': 'BTxxREDBANKBT',
            'f21': 'xxWSIX',
            'f31': 'OOxxSIXOO',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'BLxxSORCERYBL'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'GGxxTHREEGG',
            'f12': 'xxWFOUR',
            'f21': 'xxWTHREE',
            'f23': 'xxWFOUR',
            'f24': 'MMxxFOURMM',
            'f32': 'xxWTHREE',
            'reward': 'LLxxDIPLOMACYLL'},
        'On Two Fronts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxWFIVE',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'Bread and Circuses': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'LLxxFSQUARELL',
            'g34': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>', # \u2260', (tried to get != to work)
            'f13': '>',
            'f23': '>',
            'f34': '>',
            'reward': 'YYxxSTABILITYYY'},
        'Elegant Accoutrements': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'LExxFSQUARELE',
            'f21': 'xxWFOUR',
            'reward': 'xxDISGUISE'},
        'Along the Wall': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'MExxFSQUAREME',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f22': 'GTxxEMPIREGT',
            'f23': '>',
            'f33': '>',
            'reward': 'xxTACTICS'},
        'Tough Choices': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'YExxFSQUAREYE',
            'f12': 'xxWTHREE',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'reward': 'xxCOMMAND'},
        'Friend in Every Port': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'LLxxFOURLL',
            'f12': 'YYxxFOURYY',
            'f13': 'MMxxFOURMM',
            'reward': 'xxRAPPORT'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxWSIX',
            'f22': 'BTxxSETTLEDBT',
            'f32': 'xxWSIX',
            'reward': 'xxLORE'},
        'Cautious Progress': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '<',
            'f33': '<',
            'reward': 'xxTHIEVERY'},
        'Boars and Bandits': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f21': 'xxFIVE',
            'f22': 'GTxxREDBANKGT',
            'f23': 'BTxxREDBANKBT',
            'reward': 'xxCOMBAT'},
        'Ranging the Frontier': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'BSxxFSQUAREBS',
            'g21': 'GGxxFSQUAREGG',
            'g31': 'WExxFSQUAREWE',
            'f31': 'xxSETTLED',
            'reward': 'xxSURVIVAL'},
        'Expert Training': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f21': 'xxWTWO',
            'f22': 'xxWTHREE',
            'f32': 'xxWFOUR',
            'f33': 'xxWFIVE',
            'reward': 'xxCOMMITMENT'},
        'Personal Ups and Downs': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'YTxxWHREEYT',
            'f21': '<',
            'f22': '>',
            'f32': '<',
            'f33': '>',
            'reward': 'xxCOMMITMENT'},
        'Quick Wins': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': '=',
            'f31': '=',
            'reward': 'xxCOMMITMENT'},
        },
    '2': {
        'Local Investments': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'YExxFSQUAREYE', 
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'reward': 'OOxxTECHNOLOGYOO YYxxSTABILITYYY'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'reward': 'YYxxSTABILITYYY xxCOMMAND'}, 
        'Military Secrets': {
            'locregion': 'xxSETTLED', 
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BBxxSIXBB',
            'f33': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG xxTACTICS'},
        'Milk and Honey': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxWFOUR',
            'f13': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL BLxxSORCERYBL'},
        'Guidance from Crescent Hold': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OOxxONEOO',
            'f22': 'OOxxTWOOO',
            'f31': 'xxSETTLED',
            'reward': 'MMxxESPIONAGEMM xxDISGUISE'},
        'Rites of Winter': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'YYxxFSQUAREYY',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f22': 'GGxxFIVEGG',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxWSIX',
            'reward': 'LLxxDIPLOMACYLL xxRAPPORT'},
        'Marching Orders': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'YYxxFSQUAREYY',
            'g23': 'LLxxFSQUARELL',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxSETTLED',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f32': 'MTxxEMPIREMT',
            'f33': '=',
            'reward': 'GGxxMILITARYGG MMxxESPIONAGEMM'},
        'Wards Against the Deathless': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxEMPIRE',
            'f21': 'xxSETTLED',
            'f22': 'BBxxSIXBB',
            'reward': 'BLxxSORCERYBL xxLORE'},
        'Empyrean Wilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'LExxFSQUARELE',
            'f12': '>',
            'f23': '>',
            'f22': 'BTxxREDBANKBT',
            'reward': 'OOxxTECHNOLOGYOO xxSURVIVAL'},
        'Unshakable Faith': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'BExxFSQUAREBE',
            'f11': 'xxWSIX',
            'reward': 'xxCOMMITMENT xxCOMBAT'},
        'The Resistance': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'MExxFSQUAREME',
            'f11': 'xxWONE',
            'reward': 'xxCOMMITMENT xxTHIEVERY'}
        },
    '3': {
        'Keeper of Natural Lore': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWSIX',
            'f21': 'xxWSIX',
            'f31': 'xxWSIX',
            'reward': 'BLxxSORCERYBL BLxxSORCERYBL'},
        'Speaker for Red Bank': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f21': 'xxWFIVE',
            'f31': 'xxWFIVE',
            'reward': 'YYxxSTABILITYYY YYxxSTABILITYYY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f21': 'xxWONE',
            'f31': 'xxWONE',
            'reward': 'OOxxTECHNOLOGYOO OOxxTECHNOLOGYOO'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWTHREE',
            'f21': 'xxWTHREE',
            'f31': 'xxWTHREE',
            'reward': 'GGxxMILITARYGG GGxxMILITARYGG'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f21': 'xxWFOUR',
            'f31': 'xxWFOUR',
            'reward': 'LLxxDIPLOMACYLL LLxxDIPLOMACYLL'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWTWO',
            'f21': 'xxWTWO',
            'f31': 'xxWTWO',
            'reward': 'MMxxESPIONAGEMM MMxxESPIONAGEMM'},
        }
    }

card_dict_2p = {
    '1': {
        'Right Tool for the Job': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxWTWO',
            'f13': 'xxWTHREE',
            'f21': 'YYxxONEYY',
            'f23': 'YYxxSIXYY',
            'f24': 'xxWFOUR',
            'f32': 'LLxxONELL',
            'f34': 'xxWFIVE',
            'f43': 'BBxxONEBB',
            'f44': 'xxWSIX',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Empire Waning': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'GGxxFSQUAREGG',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'OOxxFSQUAREOO',
            'g24': 'OOxxFSQUAREOO',
            'g31': 'YYxxFSQUAREYY',
            'g32': 'YYxxFSQUAREYY',
            'g34': 'GGxxFSQUAREGG',
            'g42': 'GGxxFSQUAREGG',
            'g43': 'OOxxFSQUAREOO',
            'g44': 'WExxFSQUAREWE',
            'f11': 'OOxxSIXOO',
            'f12': '<',
            'f21': '<',
            'f23': '<',
            'f32': '<',
            'f34': '<',
            'f43': '<',
            'f44': 'xxWONE',
            'reward': 'MMxxESPIONAGEMM'},
        'At What Price?': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'OOxxFSQUAREOO',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'BBxxTWOBB',
            'f22': 'LLxxSIXLL',
            'f23': 'BBxxTHREEBB',
            'f33': 'MMxxSIXMM',
            'f34': 'xxSETTLED',
            'f41': 'xxREDBANK',
            'f43': 'xxREDBANK',
            'reward': 'BLxxSORCERYBL'},
        'Power Behind the Throne': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'BBxxONEBB',
            'f12': 'GGxxTWOGG',
            'f13': 'OOxxTHREEOO',
            'f24': 'OOxxTWOOO',
            'f23': 'MMxxTHREEMM',
            'f34': 'GGxxFOURGG',
            'f44': 'BBxxONEBB',
            'reward': 'LLxxDIPLOMACYLL'},
        'Hopeless Odds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'OSxxFSQUAREOS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g42': 'MMxxFSQUAREMM',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f21': 'xxREDBANK',
            'f31': 'xxSETTLED',
            'f32': 'BBxxSIXBB',
            'f43': 'xxREDBANK',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'No Margin for Error': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WExxFSQUAREWE',
            'f11': 'LLxxTHREELL',
            'f12': 'xxSETTLED',
            'f13': 'xxREDBANK',
            'f21': 'GGxxTHREEGG',
            'f24': 'xxEMPIRE',
            'f34': 'xxREDBANK',
            'f31': 'LLxxFOURLL',
            'f42': 'GGxxFIVEGG',
            'f43': 'xxWFIVE',
            'reward': 'YYxxSTABILITYYY'},
        'Safehouses': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxEMPIRE',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f23': 'OOxxTHREEOO',
            'f32': 'OOxxFOUROO',
            'f33': '=',
            'f34': 'OOxxTWOOO',
            'f43': 'OOxxTHREEOO',
            'f44': '=',
            'reward': 'xxTHIEVERY'},
        'The Resistance': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g32': 'OOxxFSQUAREOO',
            'g33': 'WWxxFSQUAREWW',
            'g44': 'OOxxFSQUAREOO',
            'f22': '<',
            'f33': '<',
            'f44': '<',
            'reward': 'xxCOMMAND'},
        'Swordcraft': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWTHREE',
            'f12': 'OOxxTWOOO',
            'f21': 'OOxxONEOO',
            'f22': '>',
            'f23': 'GGxxTHREEGG',
            'f32': 'GGxxTWOGG',
            'f33': '>',
            'f34': 'GGxxFOURGG',
            'f43': 'OOxxFOUROO',
            'f44': '>',
            'reward': 'xxCOMBAT'},
        'Hedge Magic': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'BSxxFSQUAREBS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'WExxFSQUAREWE',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'f12': '=',
            'f13': '=',
            'f14': '=',
            'f22': 'xxSETTLED',
            'f23': 'xxREDBANK',
            'reward': 'xxLORE'},
        'Mustering Aid': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'YYxxFSQUAREYY',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'LLxxFSQUARELL',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',   
            'f11': 'BBxxTWOBB',
            'f23': 'LLxxTHREELL',
            'f32': 'LLxxFOURLL',
            'f22': '>',
            'f33': '>',
            'f43': 'YYxxFIVEYY',
            'f44': '>',
            'reward': 'xxRAPPORT'},
        'Roads and Boats': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g43': 'YExxFSQUAREYE',
            'f11': 'OOxxTWOOO',
            'f12': 'xxREDBANK',
            'f22': 'OOxxTHREEOO',
            'f23': 'xxSETTLED',
            'f32': 'xxREDBANK',
            'f33': '=',
            'reward': 'xxSURVIVAL'},
        'Tools of the Trade': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f22': '=',
            'f23': 'xxSETTLED',
            'f32': 'xxEMPIRE',
            'f33': 'OOxxONEOO',
            'f44': 'OOxxFOUROO',
            'reward': 'xxDISGUISE'},
        'Trench Warfare': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'GGxxFSQUAREGG',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'YYxxFSQUAREYY',
            'g23': 'LLxxFSQUARELL',
            'g32': 'GGxxFSQUAREGG',
            'g33': 'WWxxFSQUAREWW',
            'g44': 'GExxFSQUAREGE',
            'f12': 'xxSETTLED',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f33': '=',
            'f44': '=',
            'reward': 'xxTACTICS'},
        'Taverns and Tapestries': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'LSxxFSQUARELS',
            'g12': 'YYxxFSQUAREYY',
            'g13': 'LExxFSQUARELE',
            'g22': 'BBxxFSQUAREBB',
            'f12': '>',
            'f13': '>',
            'f22': '>',
            'reward': 'xxCOMMITMENT'},
        'Mutual Sacrifice': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f22': 'BBxxSIXBB',
            'f33': 'xxWFIVE',
            'reward': 'xxCOMMITMENT'},
        'Wisdom on the Road': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f21': 'xxEMPIRE',
            'f22': 'OTxxSETTLEDOT',
            'f32': 'OTxxEMPIREOT',
            'f33': 'xxSETTLED',
            'reward': 'xxCOMMITMENT'}
        },
    '2': {
        'Metals and Guilds': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f22': 'YTxxONEYT',
            'f33': 'YTxxONEYT',
            'f44': 'xxONE',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Games Without Frontiers': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g12': 'WSxxFSQUAREWS',
            'g22': 'MMxxFSQUAREMM',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'YYxxTWOYY',
            'f42': 'xxWTWO',
            'reward': 'MMxxESPIONAGEMM'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f11': 'BTxxREDBANKBT',
            'f21': 'xxWSIX',
            'f31': 'OOxxSIXOO',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'BLxxSORCERYBL'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'GGxxTHREEGG',
            'f12': 'xxWFOUR',
            'f21': 'xxWTHREE',
            'f23': 'xxWFOUR',
            'f24': 'MMxxFOURMM',
            'f32': 'xxWTHREE',
            'reward': 'LLxxDIPLOMACYLL'},
        'On Two Fronts': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'MMxxFSQUAREMM',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxWFIVE',
            'f44': 'xxEMPIRE',
            'reward': 'GGxxMILITARYGG'},
        'Bread and Circuses': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g24': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f13': '>',
            'f24': '>',
            'reward': 'YYxxSTABILITYYY'},
        'Elegant Accoutrements': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'LExxFSQUARELE',
            'f21': 'xxWFOUR',
            'reward': 'xxDISGUISE'},
        'Along the Wall': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f22': 'GTxxEMPIREGT',
            'f23': '>',
            'f33': '>',
            'reward': 'xxTACTICS'},
        'Hard Choices': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'YExxFSQUAREYE',
            'f12': 'xxWTHREE',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'reward': 'xxCOMMAND'},
        'Empyrean Wilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': '>',
            'f23': '>',
            'f22': 'BTxxREDBANKBT',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'xxSURVIVAL'},
        'Friend in Every Port': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'LLxxFOURLL',
            'f12': 'YYxxFOURYY',
            'f13': 'MMxxFOURMM',
            'reward': 'xxRAPPORT'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxWSIX',
            'f21': 'BTxxREDBANKBT',
            'f22': 'xxWSIX',
            'f23': 'BTxxSETTLEDBT',
            'f32': 'xxWSIX',
            'reward': 'xxLORE'},
        'Expert Training': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f21': 'xxWTWO',
            'f22': 'xxWTHREE',
            'f32': 'xxWFOUR',
            'f33': 'xxWFIVE',
            'reward': 'xxCOMMITMENT'},
        'Aid the Fallen': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'GGxxFSQUAREGG',
            'g33': 'WExxFSQUAREWE',
            'f33': 'xxWFIVE',
            'reward': 'xxCOMMITMENT'},
        'Personal Ups and Downs': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'YTxxTHREEYT',
            'f21': '<',
            'f22': '>',
            'f32': '<',
            'f33': '>',
            'reward': 'xxCOMMITMENT'}
        },
    '3': {
        'Local Investments': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'WExxFSQUAREWE', 
            'f11': 'xxREDBANK',
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'reward': 'YYxxSTABILITYYY OOxxTECHNOLOGYOO'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'reward': 'YYxxSTABILITYYY LLxxDIPLOMACYLL'},
        'Rites of Winter': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWSIX',
            'f12': 'xxREDBANK',
            'f22': 'BBxxFIVEBB',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxWSIX',
            'reward': 'YYxxSTABILITYYY BLxxSORCERYBL'},
        'Boars and Bandits': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxWTHREE',
            'f21': 'xxWFIVE',
            'f22': 'GTxxREDBANKGT',
            'f23': 'BTxxREDBANKBT',
            'reward': 'YYxxSTABILITYYY GGxxMILITARYGG'},
        'Traveling Minstrels': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxEMPIRE',
            'f22': '=',
            'f23': 'xxSETTLED',
            'f32': 'xxEMPIRE',
            'f33': '=',
            'reward': 'YYxxSTABILITYYY MMxxESPIONAGEMM'},
        'Milk and Honey': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxWFOUR',
            'f13': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL OOxxTECHNOLOGYOO'},
        'Guidance from Afar': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OOxxONEOO',
            'f22': 'OOxxTWOOO',
            'f31': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL MMxxESPIONAGEMM'},
        'Cautious Progress': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '<',
            'f33': '<',
            'reward': 'LLxxDIPLOMACYLL GGxxMILITARYGG'},
        'Wards Against the Deathless': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'BBxxSIXBB',
            'f33': 'xxSETTLED',
            'reward': 'LLxxDIPLOMACYLL BLxxSORCERYBL'},
        'Military Secrets': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BBxxSIXBB',
            'f33': 'xxEMPIRE',
            'reward': 'MMxxESPIONAGEMM GGxxMILITARYGG'},
        'Cover Story': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWTWO',
            'f21': 'xxWTWO',
            'f22': 'xxWFOUR',
            'f31': 'YYxxFOURYY',
            'reward': 'MMxxESPIONAGEMM OOxxTECHNOLOGYOO'},
        'Ranging the Frontier': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'BExxFSQUAREBE',
            'f11': 'xxSETTLED',
            'reward': 'MMxxESPIONAGEMM BLxxSORCERYBL'},
        'Marching Orders': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f13': '=',
            'reward': 'GGxxMILITARYGG BLxxSORCERYBL'},
        'Research and Development': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'LLxxFSQUARELL',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f13': 'xxSETTLED',
            'reward': 'GGxxMILITARYGG OOxxTECHNOLOGYOO'},
        'Experience Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': 'xxEMPIRE',
            'f31': 'xxSETTLED',
            'reward': 'OOxxTECHNOLOGYOO BLxxSORCERYBL'},
        },
    '4': {
        'Keeper of Natural Lore': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWSIX',
            'f12': 'xxWSIX',
            'f13': 'xxWSIX',
            'f24': 'xxWSIX',
            'f34': 'xxWSIX',
            'f44': 'xxWSIX',
            'reward': 'BLxxSORCERYBL BLxxSORCERYBL'},
        'Speaker for Red Bank': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f12': 'xxWFIVE',
            'f13': 'xxWFIVE',
            'f24': 'xxWFIVE',
            'f34': 'xxWFIVE',
            'f44': 'xxWFIVE',
            'reward': 'YYxxSTABILITYYY YYxxSTABILITYYY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxWONE',
            'f13': 'xxWONE',
            'f24': 'xxWONE',
            'f34': 'xxWONE',
            'f44': 'xxWONE',
            'reward': 'OOxxTECHNOLOGYOO OOxxTECHNOLOGYOO'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWTHREE',
            'f12': 'xxWTHREE',
            'f13': 'xxWTHREE',
            'f24': 'xxWTHREE',
            'f34': 'xxWTHREE',
            'f44': 'xxWTHREE',
            'reward': 'GGxxMILITARYGG GGxxMILITARYGG'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'xxWFOUR',
            'f13': 'xxWFOUR',
            'f24': 'xxWFOUR',
            'f34': 'xxWFOUR',
            'f44': 'xxWFOUR',
            'reward': 'LLxxDIPLOMACYLL LLxxDIPLOMACYLL'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWTWO',
            'f12': 'xxWTWO',
            'f13': 'xxWTWO',
            'f24': 'xxWTWO',
            'f34': 'xxWTWO',
            'f44': 'xxWTWO',
            'reward': 'MMxxESPIONAGEMM MMxxESPIONAGEMM'},
        }
    }

original_stdout = sys.stdout

with open ("D:\\Dropbox\\Ziapelta Games\\Games\\Six Winters\\six-winters\\csv\\achievement-cards.csv", "w") as csvfile:

    sys.stdout = csvfile

    # Print csv header
    for i in range(len(columns) -1):
        print(columns[i], ',', end='', sep='')
    print(columns[-1])
    
    print()
    
    for players, card_dict in zip([1,2], [card_dict_1p, card_dict_2p]):

        # Print rows
        for next_stage in card_dict.keys():
            for next_name in card_dict[next_stage].keys():
                for next_col in columns:
                    if next_col == 'players':
                        print('"', players, '",', end='', sep='')
                    elif next_col == 'stage':
                        print('"', next_stage, '",', end='', sep='')
                    elif next_col =='name':
                        print('"', next_name, '",', end='', sep='')
                    elif next_col == 'star':
                        print('"xxSTAR",', end='', sep='')
                    else:
                        if next_col in card_dict[next_stage][next_name].keys():
                            print('"', card_dict[next_stage][next_name][next_col], '",', end='', sep='')
                        else:
                            print('""', ',', end='', sep='')
                print()
            print()
        
    sys.stdout = original_stdout