# -*- coding: utf-8 -*-
"""
Generate the achievement cards csv - kind of a pain in straight text
due to the number of grid locregions.

Created on Fri Feb 18 12:00:06 2022

@author: phill
"""

import os, sys

columns = ["stage","star","locregion","locresource","name","g11","g12","g13","g14","g21",
            "g22","g23","g24","g31","g32","g33","g34","g41","g42","g43","g44","f11","f12",
            "f13","f14","f21","f22","f23","f24","f31","f32","f33","f34","f41","f42","f43","f44","reward","bonus"]
    
stars_per_stage = {'1': 'xxCARDxxCARD', '2': 'xxCARD', '3': 'xxCARDxxCARD', '4': 'xxCARDxxCARDxxCARD', '5': 'xxCARDxxCARDxxCARD', 'xxDIPLOMACY': ''}

card_dict = {
    '1': {
        'Tinkering': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f12': 'xxEMPIRE',
            'f22': 'xxSETTLED',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Flora, Fauna, and Fiends': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'BBxxFSQUAREBB',
            'g23': 'WExxFSQUAREWE',
            'f12': 'xxWSIX',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Thieves Tools': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f12': 'xxEMPIRE',
            'f22': 'xxREDBANK',
            'f23': 'xxEMPIRE',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'MMxxESPIONAGEMM'},
        'Out in the Cold': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxEMPIRE',
            'f21': 'xxWONE',
            'f22': 'xxWTWO',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'MMxxESPIONAGEMM'},
        'Cantrips': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxSETTLED',
            'f33': 'xxREDBANK',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'BLxxSORCERYBL'},
        'Thedda\'s Palimpsest': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'BSxxFSQUAREBS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxSETTLED',
            'f22': 'xxWSIX',
            'f23': 'xxSETTLED',
            'bonus': 'RBxxFSQUARERB',
            'reward': ' BLxxSORCERYBL'},
        'Grand Tour': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'GSxxFSQUAREGS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'BBxxFSQUAREBB',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'LLxxDIPLOMACYLL'},
        'Small Steps': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f21': '+1',
            'f23': '-1',
            'f32': '=',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'LLxxDIPLOMACYLL'},
        'Warmachine': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'MSxxFSQUAREMS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': 'xxEMPIRE',
            'f22': 'xxREDBANK',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'GGxxMILITARYGG'},
        'Tactical Plans': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxEMPIRE',
            'f22': 'xxWFIVE',
            'f23': 'xxREDBANK',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'GGxxMILITARYGG'},
        'Friends at Home and Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'LSxxFSQUARELS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'BBxxFSQUAREBB',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxREDBANK',
            'f23': 'xxREDBANK',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'YYxxSTABILITYYY'},
        'Uplifting Words': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'GGxxFSQUAREGG',
            'g22': 'LLxxFSQUARELL',
            'g31': 'WExxFSQUAREWE',
            'f31': 'xxREDBANK',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY'}
        },
    '2': {
        'Metals and Guilds': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f22': 'YTxxONEYT',
            'f33': 'YTxxONEYT',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Games Without Frontiers': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g12': 'MSxxFSQUAREMS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f22': 'YYxxTWOYY',
            'f34': 'xxWTWO',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'MMxxESPIONAGEMM'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f22': 'BTxxREDBANKBT',
            'f21': 'xxWSIX',
            'f31': 'OOxxSIXOO',
            'f33': 'BTxxSETTLEDBT',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'BLxxSORCERYBL'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'MMxxFOURMM',
            'f21': 'xxWTHREE',
            'f23': 'xxWFOUR',
            'f32': 'GGxxTHREEGG',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'LLxxDIPLOMACYLL'},
        'On Two Fronts': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'MMxxFSQUAREMM',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxWFIVE',
            'f44': 'xxEMPIRE',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'GGxxMILITARYGG'},
        'Bread and Circuses': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g24': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '+1',
            'f13': '+1',
            'f24': '+1',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'YYxxSTABILITYYY'},
        'Hard Choices': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'MMxxFSQUAREMM',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'YExxFSQUAREYE',
            'f11': 'xxWTHREE',
            'f12': 'OTxxSETTLEDOT',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'f34': '+1',
            'f43': '-1',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'f12': 'xxWSIX',
            'f21': 'BTxxREDBANKBT',
            'f22': 'xxWSIX',
            'f23': 'BTxxSETTLEDBT',
            'f31': 'LLxxFOURLL',
            'f32': 'xxWSIX',
            'f33': 'MMxxTWOMM',
            'f42': 'xxWSIX',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'}
        },
    '3': {
        'Right Tool for the Job': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxWTWO',
            'f13': 'xxWTHREE',
            'f21': 'YYxxONEYY',
            'f23': 'YYxxSIXYY',
            'f24': 'xxWFOUR',
            'f32': 'LLxxONELL',
            'f34': 'xxWFIVE',
            'f43': 'BBxxONEBB',
            'f44': 'xxWSIX',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'OOxxTECHNOLOGYOO'},
        'Empire Waning': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'GGxxFSQUAREGG',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'OOxxFSQUAREOO',
            'g24': 'OOxxFSQUAREOO',
            'g31': 'YYxxFSQUAREYY',
            'g32': 'YYxxFSQUAREYY',
            'g34': 'GGxxFSQUAREGG',
            'g42': 'GGxxFSQUAREGG',
            'g43': 'OOxxFSQUAREOO',
            'g44': 'WExxFSQUAREWE',
            'f12': '+1',
            'f21': '-1',
            'f23': '+1',
            'f32': '-1',
            'f34': '+1',
            'f43': '-1',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'MMxxESPIONAGEMM'},
        'At What Price?': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'BBxxTWOBB',
            'f22': 'LLxxSIXLL',
            'f23': 'BBxxTHREEBB',
            'f33': 'MMxxSIXMM',
            'f34': 'xxSETTLED',
            'f41': 'xxREDBANK',
            'f42': '+1',
            'f43': 'xxREDBANK',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'BLxxSORCERYBL'},
        'Power Behind the Throne': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'GGxxTWOGG',
            'f13': 'OOxxTHREEOO',
            'f21': 'BBxxSIXBB',
            'f24': 'OOxxTWOOO',
            'f23': 'MMxxTHREEMM',
            'f31': 'BBxxSIXBB',
            'f32': 'GGxxFIVEGG',
            'f34': 'GGxxFOURGG',
            'f42': 'BBxxSIXBB',
            'f43': 'MMxxTWOMM',
            'f44': 'xxWFOUR',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'LLxxDIPLOMACYLL'},
        'Hopeless Odds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'OSxxFSQUAREOS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g42': 'MMxxFSQUAREMM',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f21': 'xxREDBANK',
            'f31': 'xxSETTLED',
            'f32': 'BBxxSIXBB',
            'f43': 'xxREDBANK',
            'f44': 'xxEMPIRE',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'GGxxMILITARYGG'},
        'No Margin for Error': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WExxFSQUAREWE',
            'f11': 'xxWTHREE',
            'f12': 'xxSETTLED',
            'f13': 'xxREDBANK',
            'f21': 'GGxxTHREEGG',
            'f23': 'BBxxSIXBB',
            'f24': 'xxEMPIRE',
            'f34': 'xxREDBANK',
            'f31': 'LLxxFOURLL',
            'f42': 'GGxxFIVEGG',
            'f43': 'xxWFIVE',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY'},
        'Safehouses': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxEMPIRE',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f23': 'OOxxTHREEOO',
            'f32': 'OOxxFOUROO',
            'f33': '=',
            'f34': 'OOxxTWOOO',
            'f43': 'OOxxTHREEOO',
            'f44': '=',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'The Resistance': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g23': 'MMxxFSQUAREMM',
            'g24': 'GGxxFSQUAREGG',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g41': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'OExxFSQUAREOE',
            'f12': '+1',
            'f13': '+1',
            'f23': '+1',
            'f24': '+1',
            'f31': '-1',
            'f32': 'OOxxONEOO',
            'f34': '+1',
            'f42': '-1',
            'f43': 'LLxxTHREELL',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'},
        'Mustering Aid': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'YYxxFSQUAREYY',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',   
            'f11': 'xxWFIVE',
            'f12': 'GGxxFOURGG',
            'f23': 'LLxxTHREELL',
            'f31': '+1',
            'f32': 'LLxxFOURLL',
            'f34': 'GGxxFIVEGG',
            'f42': '+1',
            'f43': 'YYxxFIVEYY',
            'f44': 'xxWFIVE',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Wisdom on the Road': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxWFIVE',
            'f13': 'LLxxFOURLL',
            'f21': 'xxSETTLED',
            'f24': 'OTxxSETTLEDOT',
            'f31': 'xxEMPIRE',
            'f34': 'GGxxTHREEGG',
            'f42': 'OOxxTWOOO',
            'f43': 'xxWSIX',
            'f44': 'xxSETTLED',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'}
        },
    '4': {
        'Local Investments': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'WExxFSQUAREWE', 
            'f11': 'xxREDBANK',
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY OOxxTECHNOLOGYOO'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY LLxxDIPLOMACYLL'},
        'Rites of Winter': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxWSIX',
            'f12': 'xxREDBANK',
            'f22': 'BBxxFIVEBB',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxWSIX',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY BLxxSORCERYBL'},
        'Boars and Bandits': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxWTHREE',
            'f21': 'xxWFIVE',
            'f22': 'GTxxREDBANKGT',
            'f23': 'BTxxREDBANKBT',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY GGxxMILITARYGG'},
        'Traveling Minstrels': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxEMPIRE',
            'f22': '=',
            'f23': 'xxSETTLED',
            'f32': 'xxEMPIRE',
            'f33': '=',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY MMxxESPIONAGEMM'},
        'Milk and Honey': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxWFOUR',
            'f13': 'xxSETTLED',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'LLxxDIPLOMACYLL OOxxTECHNOLOGYOO'},
        'Guidance from Afar': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OOxxONEOO',
            'f22': 'OOxxTWOOO',
            'f31': 'xxSETTLED',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'LLxxDIPLOMACYLL MMxxESPIONAGEMM'},
        'Cautious Progress': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '-1',
            'f33': '-1',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'LLxxDIPLOMACYLL GGxxMILITARYGG'},
        'Wards Against the Deathless': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'BBxxSIXBB',
            'f33': 'xxSETTLED',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'LLxxDIPLOMACYLL BLxxSORCERYBL'},
        'Military Secrets': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BBxxSIXBB',
            'f33': 'xxEMPIRE',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'MMxxESPIONAGEMM GGxxMILITARYGG'},
        'Cover Story': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f11': 'xxWTWO',
            'f21': 'xxWTWO',
            'f22': 'xxWFOUR',
            'f31': 'YYxxFOURYY',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'MMxxESPIONAGEMM OOxxTECHNOLOGYOO'},
        'Ranging the Frontier': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'BExxFSQUAREBE',
            'f11': 'xxSETTLED',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'MMxxESPIONAGEMM BLxxSORCERYBL'},
        'Marching Orders': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f13': '=',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'GGxxMILITARYGG BLxxSORCERYBL'},
        'Research and Development': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'LLxxFSQUARELL',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f13': 'xxSETTLED',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'GGxxMILITARYGG OOxxTECHNOLOGYOO'},
        'Experience Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': 'xxEMPIRE',
            'f31': 'xxSETTLED',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'OOxxTECHNOLOGYOO BLxxSORCERYBL'},
        },
    '5': {
        'Keeper of Natural Lore': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWSIX',
            'f12': 'xxWSIX',
            'f13': 'xxWSIX',
            'f24': 'xxWSIX',
            'f34': 'xxWSIX',
            'f44': 'xxWSIX',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'BLxxSORCERYBL BLxxSORCERYBL'},
        'Speaker for Sunbridle': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWFIVE',
            'f12': 'xxWFIVE',
            'f13': 'xxWFIVE',
            'f24': 'xxWFIVE',
            'f34': 'xxWFIVE',
            'f44': 'xxWFIVE',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'YYxxSTABILITYYY YYxxSTABILITYYY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWONE',
            'f12': 'xxWONE',
            'f13': 'xxWONE',
            'f24': 'xxWONE',
            'f34': 'xxWONE',
            'f44': 'xxWONE',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'OOxxTECHNOLOGYOO OOxxTECHNOLOGYOO'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWTHREE',
            'f12': 'xxWTHREE',
            'f13': 'xxWTHREE',
            'f24': 'xxWTHREE',
            'f34': 'xxWTHREE',
            'f44': 'xxWTHREE',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'GGxxMILITARYGG GGxxMILITARYGG'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWFOUR',
            'f12': 'xxWFOUR',
            'f13': 'xxWFOUR',
            'f24': 'xxWFOUR',
            'f34': 'xxWFOUR',
            'f44': 'xxWFOUR',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'LLxxDIPLOMACYLL LLxxDIPLOMACYLL'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxWTWO',
            'f12': 'xxWTWO',
            'f13': 'xxWTWO',
            'f24': 'xxWTWO',
            'f34': 'xxWTWO',
            'f44': 'xxWTWO',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'MMxxESPIONAGEMM MMxxESPIONAGEMM'},
        'The Path of Magic': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'BBxxFSQUAREBB',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f12': '+1',
            'f13': '+1',
            'f24': '+1',
            'f34': '+1',
            'f44': '=',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'xxSTAR'},
        'The Path of Technology': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'OOxxFSQUAREOO',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f12': '-1',
            'f13': '-1',
            'f24': '-1',
            'f34': '-1',
            'f44': '=',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Settled Lands Tour': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'LSxxFSQUARELS',
            'g12': 'OOxxFSQUAREOO',
            'g13': 'OOxxFSQUAREOO',
            'g14': 'LLxxFSQUARELL',
            'g24': 'BBxxFSQUAREBB',
            'g34': 'BBxxFSQUAREBB',
            'g44': 'LExxFSQUARELE',
            'f12': '-1',
            'f13': '-1',
            'f24': '-1',
            'f34': '-1',
            'f44': '-1',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'},
        'Sunbridle Tour': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY##NBSP##',
            'g11': 'GSxxFSQUAREGS',
            'g12': 'YYxxFSQUAREYY',
            'g13': 'YYxxFSQUAREYY',
            'g14': 'GGxxFSQUAREGG',
            'g24': 'BBxxFSQUAREBB',
            'g34': 'BBxxFSQUAREBB',
            'g44': 'GExxFSQUAREGE',
            'f12': '+1',
            'f13': '+1',
            'f24': '+1',
            'f34': '+1',
            'f44': '+1',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'xxSTAR'},
        'Imperial Tour': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'GSxxFSQUAREGS',
            'g12': 'OOxxFSQUAREOO',
            'g13': 'OOxxFSQUAREOO',
            'g14': 'GGxxFSQUAREGG',
            'g24': 'MMxxFSQUAREMM',
            'g34': 'MMxxFSQUAREMM',
            'g44': 'GExxFSQUAREGE',
            'f12': '=',
            'f13': '=',
            'f24': '=',
            'f34': '=',
            'f44': '=',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Potions or Promises': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'LLxxFSQUARELL',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g21': 'BBxxFSQUAREBB',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'LLxxFSQUARELL',
            'g41': 'BBxxFSQUAREBB',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'BBxxFSQUAREBB',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'},
        'Swords or Sorcery': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'GGxxFSQUAREGG',
            'g21': 'BBxxFSQUAREBB',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g41': 'BBxxFSQUAREBB',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'BBxxFSQUAREBB',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'xxSTAR'},
        'Secrets or Stability': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'MMxxFSQUAREMM',
            'g21': 'YYxxFSQUAREYY',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'MMxxFSQUAREMM',
            'g41': 'YYxxFSQUAREYY',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'YYxxFSQUAREYY',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Catapults or Conversations': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g41': 'LLxxFSQUARELL',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'EMxxFSQUAREEM',
            'reward': 'xxSTAR'},
        'Traps or Tech': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'MMxxFSQUAREMM',
            'g21': 'OOxxFSQUAREOO',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'MMxxFSQUAREMM',
            'g41': 'OOxxFSQUAREOO',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'OOxxFSQUAREOO',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '=',
            'f24': '-1',
            'f42': '=',
            'f44': '=',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'},
        'Halberds or Happiness': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'GGxxFSQUAREGG',
            'g21': 'YYxxFSQUAREYY',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g41': 'YYxxFSQUAREYY',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'YYxxFSQUAREYY',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'RBxxFSQUARERB',
            'reward': 'xxSTAR'},
        'Home or Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY##NBSP##',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'YYxxFSQUAREYY',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'YYxxFSQUAREYY',
            'g21': 'LLxxFSQUARELL',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'YYxxFSQUAREYY',
            'g41': 'LLxxFSQUARELL',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f13': '-1',
            'f31': '+1',
            'f24': '-1',
            'f42': '+1',
            'f44': '=',
            'bonus': 'SLxxFSQUARESL',
            'reward': 'xxSTAR'},
        },
    'xxDIPLOMACY': {
        'Beyond Brightdune': {
            'locregion': '',
            'locresource': '',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'f12': 'LLxxFOURLL',
            'f13': 'LLxxFIVELL',
            'f24': 'LLxxSIXLL',
            'f43': '+1',
            'f42': '+1',
            'f41': '+1',
            'bonus': '',
            'reward': ''},
    }
}

original_stdout = sys.stdout

with open (".\\csv\\progress-cards.csv", "w") as csvfile:

    sys.stdout = csvfile

    # Print csv header
    for i in range(len(columns) -1):
        print(columns[i], ',', end='', sep='')
    print(columns[-1])
    
    print()

    # Print rows
    for next_stage in card_dict.keys():
        for next_name in card_dict[next_stage].keys():
            for next_col in columns:
                if next_col == 'players':
                    print('"xxPLAYER",', end='', sep='')
                elif next_col == 'stage':
                    print('"', next_stage, '",', end='', sep='')
                elif next_col =='name':
                    print('"', next_name, '",', end='', sep='')
                elif next_col == 'star':
                    print('"', stars_per_stage[next_stage], '",', end='', sep='')
                else:
                    if next_col in card_dict[next_stage][next_name].keys():
                        print('"', card_dict[next_stage][next_name][next_col], '",', end='', sep='')
                    else:
                        print('""', ',', end='', sep='')
            print()
        print()
        
    sys.stdout = original_stdout

locs_by_stage = {}

for next_stage in card_dict.keys():
    locs_by_stage[next_stage] = {}
    for next_name in card_dict[next_stage].keys():
        locs_by_stage[next_stage][card_dict[next_stage][next_name]['locregion'] + card_dict[next_stage][next_name]['locresource']] = 0

for next_stage in card_dict.keys():
    for next_name in card_dict[next_stage].keys():
        loc_key = card_dict[next_stage][next_name]['locregion'] + card_dict[next_stage][next_name]['locresource']
        locs_by_stage[next_stage][loc_key] = locs_by_stage[next_stage][loc_key] + 1

loc_keys = ['xxEMPIRExxMILITARY', 'xxEMPIRExxTECHNOLOGY', 'xxEMPIRExxESPIONAGE', 'xxREDBANKxxMILITARY', 'xxREDBANKxxSTABILITY', 
            'xxREDBANKxxSORCERY', 'xxSETTLEDxxDIPLOMACY', 'xxSETTLEDxxTECHNOLOGY', 'xxSETTLEDxxSORCERY']

for next_stage in locs_by_stage.keys():
    total = 0
    print()
    print(next_stage)
    for count, next_loc in enumerate(loc_keys):
        if count % 3 == 0:
            print()
        if next_loc in locs_by_stage[next_stage].keys():
            print(next_loc, locs_by_stage[next_stage][next_loc])
            total = total + locs_by_stage[next_stage][next_loc]
        else:
            print(next_loc, "0")
    print(total)