# -*- coding: utf-8 -*-
"""
Generate the achievement cards csv - kind of a pain in straight text
due to the number of grid locregions.

Created on Fri Feb 18 12:00:06 2022

@author: phill
"""

import sys

columns = ["stage","star","locregion","locresource","name","g11","g12","g13","g14","g21","g22","g23","g24","g31","g32","g33","g34","g41","g42","g43","g44","f11","f12","f13","f14","f21","f22","f23","f24","f31","f32","f33","f34","f41","f42","f43","f44","reward"]
    
card_dict = {
    '1': {
        'Local Investments': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW', 
            'g21': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'WWxxFSQUAREWW', 
            'g32': 'WWxxFSQUAREWW', 
            'g33': 'YExxFSQUAREYE', 
            'f23': 'xxEMPIRE', 
            'f32': 'xxSETTLED', 
            'reward': 'xxTECHNOLOGY'
            }, 
        'Forging Bonds': {
            'locregion': 'xxREDBANK', 
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'WWxxFSQUAREWW', 
            'g22': 'LLxxFSQUARELL', 
            'g23': 'MMxxFSQUAREMM', 
            'g33': 'WExxFSQUAREWE',
            'f12': 'xxREDBANK',
            'f33': 'xxSETTLED',
            'reward': 'xxSTABILITY'}, 
        'Military Secrets': {
            'locregion': 'xxEMPIRE', 
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS', 
            'g12': 'MMxxFSQUAREMM',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'MMxxFSQUAREMM',
            'g33': 'WExxFSQUAREWE',
            'f22': 'BTxxSIXBT',
            'f33': 'xxEMPIRE',
            'reward': 'xxMILITARY'},
        'Milk and Honey': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxFOUR',
            'f13': 'xxSETTLED',
            'reward': 'xxDIPLOMACY'},
        'Guidance from Crescent Hold': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'xxEMPIRE',
            'f21': 'OTxxONEOT',
            'f22': 'OTxxTWOOT',
            'f31': 'xxSETTLED',
            'reward': 'xxESPIONAGE'},
        'Rites of Winter': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f12': 'YTxxREDBANKYT',
            'f22': 'BTxxBODYBT',
            'f23': 'BTxxSETTLEDBT',
            'f33': 'xxSIX',
            'reward': 'xxSORCERY'},
        'Marching Orders': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f12': '',
            'reward': 'xxTACTICS'},
        'Cautious Progress': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g33': 'OExxFSQUAREOE',
            'f22': '<',
            'f33': '<',
            'reward': 'xxTHIEVERY'},
        'Traveling Minstrels': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f22': '=',
            'f23': 'xxSETTLED',
            'f32': 'xxEMPIRE',
            'f33': '=',
            'reward': 'xxDISGUISE'},
        'Boars and Bandits': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f21': 'xxFIVE',
            'f22': 'GTxxREDBANKGT',
            'f23': 'BTxxREDBANKBT',
            'reward': 'xxCOMBAT'},
        'Local Repairs': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': 'xxTHREE',
            'f22': 'xxFOUR',
            'f31': 'YTxxTHREEYT',
            'reward': 'xxCOMMAND'},
        'Ranging the Frontier': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'GExxFSQUAREGE',
            'f11': 'xxBODY',
            'reward': 'xxSURVIVAL'},
        'Foreign Etiquette': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'LExxFSQUARELE',
            'f11': 'xxFOUR',
            'reward': 'xxRAPPORT'},
        'Wards Against the Deathless': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': 'xxBODY',
            'f21': 'xxPSYCHE',
            'f22': 'BTxxSIXBT',
            'f23': 'xxBODY',
            'f32': 'xxPSYCHE',
            'reward': 'xxLORE'},
        'Experience Abroad': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WExxFSQUAREWE',
            'f21': 'xxEMPIRE',
            'reward': 'xxCOMMITMENT'},
        'Unshakable Faith': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'BExxFSQUAREBE',
            'f11': 'xxSIX',
            'reward': 'xxCOMMITMENT'},
        'Quick Wins': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WExxFSQUAREWE',
            'f21': '=',
            'f31': '=',
            'reward': 'xxCOMMITMENT'}
        },
    '2': {
        'Metals and Guilds': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g21': 'LLxxFSQUARELL',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'GGxxFSQUAREGG',
            'g32': 'LLxxFSQUARELL',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'GGxxFSQUAREGG',
            'g43': 'LLxxFSQUARELL',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f22': 'YTxxONEYT',
            'f33': 'YTxxONEYT',
            'f44': 'xxONE',
            'reward': 'xxTECHNOLOGY'},
        'Games Without Frontiers': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'YTxxTWOYT',
            'f21': 'MTxxEMPIREMT',
            'f22': 'xxPSYCHE',
            'f23': 'GTxxEMPIREGT',
            'f32': 'OTxxEMPIREOT',
            'f42': 'xxTWO',
            'reward': 'xxESPIONAGE'},
        'Priming the Mana Forge': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g41': 'WExxFSQUAREWE',
            'g42': 'WWxxFSQUAREWW',
            'f11': 'BTxxREDBANKBT',
            'f21': 'xxPSYCHE',
            'f31': 'OTxxPSYCHEOT',
            'f33': 'BTxxSETTLEDBT',
            'reward': 'xxSORCERY'},
        'Talk of War': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g32': 'WWxxFSQUAREWW',
            'f11': 'GTxxTHREEGT',
            'f12': 'xxFOUR',
            'f21': 'xxTHREE',
            'f23': 'xxFOUR',
            'f24': 'MTxxFOURMT',
            'f32': 'xxTHREE',
            'reward': 'xxDIPLOMACY'},
        'On Two Fronts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f22': 'xxFIVE',
            'f44': 'xxEMPIRE',
            'reward': 'xxMILITARY'},
        'Bread and Circuses': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'LLxxFSQUARELL',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f13': '>',
            'f24': '>',
            'f34': '>',
            'reward': 'xxSTABILITY'},
        'Elegant Accoutrements': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'YSxxFSQUAREYS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'LExxFSQUARELE',
            'f21': 'xxFOUR',
            'reward': 'xxDISGUISE'},
        'Further Sacrifices': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g12': 'WSxxFSQUAREWS',
            'g22': 'MMxxFSQUAREMM',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'OOxxFSQUAREOO',
            'g34': 'WWxxFSQUAREWW',
            'g42': 'WExxFSQUAREWE',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'xxONE',
            'f22': 'xxPSYCHE',
            'f23': '>',
            'f34': '>',
            'f42': 'xxONE',
            'f43': '>',
            'reward': 'xxTHIEVERY'},
        'Along the Wall': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f12': '>',
            'f22': 'GTxxEMPIREGT',
            'f23': '>',
            'f33': '>',
            'reward': 'xxCOMBAT'},
        'Hard Choices': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'LLxxFSQUARELL',
            'g32': 'YExxFSQUAREYE',
            'f12': 'xxTHREE',
            'f21': 'GTxxEMPIREGT',
            'f22': 'BTxxREDBANKBT',
            'reward': 'xxCOMMAND'},
        'Empyrean Wilds': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WExxFSQUAREWE',
            'f12': '>',
            'f13': '>',
            'f22': 'BTxxREDBANKBT',
            'f33': 'BTxxSETTLEDBT',
            'f24': '>',
            'reward': 'xxSURVIVAL'},
        'Friend in Every Port': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WExxFSQUAREWE',
            'f11': 'LTxxFOURLT',
            'f12': 'YTxxFOURYT',
            'f13': 'MTxxFOURMT',
            'reward': 'xxRAPPORT'},
        'Rebel Sacrifice': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g24': 'WExxFSQUAREWE',
            'g33': 'WWxxFSQUAREWW',
            'f12': 'GTxxEMPIREGT',
            'f13': 'OTxxEMPIREOT',
            'f22': 'xxFIVE',
            'f33': 'xxBODY',
            'reward': 'xxTACTICS'},
        'Sorcerous Shortcuts': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g12': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f12': 'xxSIX',
            'f21': 'BTxxBODYBT',
            'f22': 'xxSIX',
            'f23': 'BTxxPSYCHEBT',
            'f32': 'xxSIX',
            'reward': 'xxLORE'},
        'Expert Training': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f21': 'xxTWO',
            'f22': 'xxTHREE',
            'f32': 'xxFOUR',
            'f33': 'xxFIVE',
            'reward': 'xxCOMMITMENT'},
        'Personal Ups and Downs': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'YTxxTHREEYT',
            'f21': '<',
            'f22': '>',
            'f32': '<',
            'f33': '>',
            'reward': 'xxCOMMITMENT'}
        },
    '3': {
        'Right Tool for the Job': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxTWO',
            'f13': 'xxTHREE',
            'f24': 'xxFOUR',
            'f34': 'xxFIVE',
            'f44': 'xxSIX',
            'reward': 'xxTECHNOLOGY xxSTABILITY'},
        'Empire Waning': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'GGxxFSQUAREGG',
            'g14': 'WWxxFSQUAREWW',
            'g21': 'MMxxFSQUAREMM',
            'g24': 'OOxxFSQUAREOO',
            'g31': 'YYxxFSQUAREYY',
            'g34': 'GGxxFSQUAREGG',
            'g41': 'WWxxFSQUAREWW',
            'g42': 'GGxxFSQUAREGG',
            'g43': 'YYxxFSQUAREYY',
            'g44': 'WExxFSQUAREWE',
            'f11': 'OTxxFIVEOT',
            'f12': '<',
            'f13': '<',
            'f14': 'xxREDBANK',
            'f21': '<',
            'f24': '<',
            'f31': '<',
            'f34': '<',
            'f41': 'xxSETTLED',
            'f42': '<',
            'f43': '<',
            'f44': 'MTxxTWOMT',
            'reward': 'xxESPIONAGE xxMILITARY'},
        'At What Price?': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'YSxxFSQUAREYS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'BExxFSQUAREBE',
            'g42': 'OOxxFSQUAREOO',
            'g43': 'WWxxFSQUAREWW',
            'f12': 'xxBODY',
            'f22': 'LTxxSIXLT',
            'f23': 'xxPSYCHE',
            'f32': 'xxDISCORD',
            'f33': 'MTxxSIXMT',
            'f34': 'xxBODY',
            'f43': 'xxPSYCHE',
            'reward': 'xxSORCERY xxDIPLOMACY'},
        'Power Behind the Throne': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'BTxxONEBT',
            'f12': 'MTxxTWOMT',
            'f13': 'YTxxTHREEYT',
            'f24': 'OTxxTWOOT',
            'f23': 'LTxxTHREELT',
            'f34': 'GTxxFOURGT',
            'f44': 'BTxxONEBT',
            'reward': 'xxDIPLOMACY xxTECHNOLOGY'},
        'Arcane Logistics': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'GTxxEMPIREGT',
            'f21': 'GTxxREDBANKGT',
            'f31': 'BTxxSETTLEDBT',
            'f32': 'BTxxBODYBT',
            'f42': 'GTxxEMPIREGT',
            'f43': 'GTxxREDBANKGT',
            'f44': 'BTxxREDBANKBT',
            'reward': 'xxMILITARY xxSORCERY'},
        'No Margin for Error': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g12': 'WSxxFSQUAREWS',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WWxxFSQUAREWW',
            'f12': 'LTxxTHREELT',
            'f22': 'YTxxFOURYT',
            'f32': 'MTxxTWOMT',
            'f43': 'xxFIVE',
            'f44': 'xxSIX',
            'reward': 'xxSTABILITY xxESPIONAGE'},
        'Safehouses': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxEMPIRE',
            'f21': 'xxEMPIRE',
            'f22': '=',
            'f23': 'OTxxTHREEOT',
            'f32': 'OTxxFOUROT',
            'f33': '=',
            'f34': 'OTxxTWOOT',
            'f43': 'OTxxTHREEOT',
            'f44': '=',
            'reward': 'xxESPIONAGE xxDISGUISE'},
        'The Resistance': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'WWxxFSQUAREWW',
            'g21': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g31': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g41': 'WWxxFSQUAREWW',
            'g42': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WWxxFSQUAREWW',
            'f11': 'xxREDBANK',
            'f12': '<',
            'f13': '<',
            'f14': 'MTxxEMPIREMT',
            'f21': '<',
            'f24': '<',
            'f31': '<',
            'f34': '<',
            'f41': 'OTxxEMPIREOT',
            'f42': '<',
            'f43': '<',
            'f44': 'xxREDBANK',
            'reward': 'xxSTABILITY xxTHIEVERY'},
        'Swordcraft': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f21': 'OTxxONEOT',
            'f22': '>',
            'f23': 'GTxxTHREEGT',
            'f32': 'GTxxTWOGT',
            'f33': '>',
            'f34': 'GTxxFOURGT',
            'f43': 'OTxxFOUROT',
            'f44': '>',
            'reward': 'xxMILITARY xxCOMBAT'},
        'Mustering Aid': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',   
            'f11': 'BTxxTHREEBT',
            'f12': 'YTxxONEYT',
            'f21': 'YTxxSETTLEDYT',
            'f23': 'LTxxTHREELT',
            'f32': 'LTxxTWOLT',
            'f34': 'LTxxSETTLEDLT',
            'f43': 'YTxxFOURYT',
            'f22': '>',
            'f33': '>',
            'f44': '>',
            'reward': 'xxDIPLOMACY xxCOMMAND'},
        'Hidden Forts': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g23': 'WWxxFSQUAREWW',
            'g32': 'WExxFSQUAREWE',
            'f11': 'OTxxTWOOT',
            'f12': 'xxREDBANK',
            'f22': 'OTxxTHREEOT',
            'f23': 'xxREDBANK',
            'f32': 'xxSETTLED',
            'reward': 'xxSURVIVAL xxLORE'},
        'Taverns and Tapestries': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'YYxxFSQUAREYY',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WExxFSQUAREWE',
            'g44': 'YYxxFSQUAREYY',
            'f12': '<',
            'f13': '<',
            'f24': '<',
            'f34': '<',
            'f43': '<',
            'reward': 'xxCOMMAND xxRAPPORT'},
        'Mutual Sacrifice': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'GGxxFSQUAREGG',
            'g22': 'WWxxFSQUAREWW',
            'g24': 'YYxxFSQUAREYY',
            'g33': 'WWxxFSQUAREWW',
            'g34': 'YYxxFSQUAREYY',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f22': 'GTxxBODYGT',
            'f33': 'GTxxBODYGT',
            'f44': 'xxFIVE',
            'reward': 'xxTECHNOLOGY xxTACTICS'},
        'Hedge Magic': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'BSxxFSQUAREBS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g14': 'BBxxFSQUAREBB',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g43': 'WExxFSQUAREWE',
            'g44': 'BBxxFSQUAREBB',
            'f12': '=',
            'f13': '=',
            'f24': '=',
            'f34': '=',
            'f43': '=',
            'reward': 'xxSORCERY xxLORE'},
        'Wisdom on the Road': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g21': 'WWxxFSQUAREWW',
            'g22': 'WWxxFSQUAREWW',
            'g32': 'WWxxFSQUAREWW',
            'g33': 'WExxFSQUAREWE',
            'f11': 'xxREDBANK',
            'f21': 'xxEMPIRE',
            'f22': 'OTxxSETTLEDOT',
            'f32': 'OTxxEMPIREOT',
            'f33': 'xxSETTLED',
            'reward': 'xxCOMMITMENT xxCOMMITMENT'}
        },
    '4': {
        'Keeper of Natural Lore': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxSORCERY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxSIX',
            'f12': 'xxSIX',
            'f13': 'xxSIX',
            'f24': 'xxSIX',
            'f34': 'xxSIX',
            'f44': 'xxSIX',
            'reward': 'xxSORCERY xxSORCERY'},
        'Speaker for Red Bank': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSTABILITY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFIVE',
            'f12': 'xxFIVE',
            'f13': 'xxFIVE',
            'f24': 'xxFIVE',
            'f34': 'xxFIVE',
            'f44': 'xxFIVE',
            'reward': 'xxSTABILITY xxSTABILITY'},
        'At Any Cost': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxSORCERY',
            'g11': 'LSxxFSQUARELS',
            'g12': 'GGxxFSQUAREGG',
            'g13': 'MMxxFSQUAREMM',
            'g24': 'LLxxFSQUARELL',
            'g34': 'GGxxFSQUAREGG',
            'g44': 'MExxFSQUAREME',
            'reward': 'xxSTABILITY xxSTABILITY'},
        'Archer of the Amber Hand': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxONE',
            'f12': 'xxONE',
            'f13': 'xxONE',
            'f24': 'xxONE',
            'f34': 'xxONE',
            'f44': 'xxONE',
            'reward': 'xxTECHNOLOGY xxTECHNOLOGY'},
        'Hawkleader of the Ghost Legion': {
            'locregion': 'xxREDBANK',
            'locresource': 'xxMILITARY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxTHREE',
            'f12': 'xxTHREE',
            'f13': 'xxTHREE',
            'f24': 'xxTHREE',
            'f34': 'xxTHREE',
            'f44': 'xxTHREE',
            'reward': 'xxMILITARY xxMILITARY'},
        'Master of Coin': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxDIPLOMACY',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxFOUR',
            'f12': 'xxFOUR',
            'f13': 'xxFOUR',
            'f24': 'xxFOUR',
            'f34': 'xxFOUR',
            'f44': 'xxFOUR',
            'reward': 'xxDIPLOMACY xxDIPLOMACY'},
        'Agents and Arrows': {
            'locregion': 'xxSETTLED',
            'locresource': 'xxTECHNOLOGY',
            'g11': 'GSxxFSQUAREGS',
            'g12': 'MMxxFSQUAREMM',
            'g13': 'OOxxFSQUAREOO',
            'g24': 'GGxxFSQUAREGG',
            'g34': 'MMxxFSQUAREMM',
            'g44': 'OExxFSQUAREOE',
            'reward': 'xxDIPLOMACY xxDIPLOMACY'},
        'Traitor of Southkeep': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxESPIONAGE',
            'g11': 'WSxxFSQUAREWS',
            'g12': 'WWxxFSQUAREWW',
            'g13': 'WWxxFSQUAREWW',
            'g24': 'WWxxFSQUAREWW',
            'g34': 'WWxxFSQUAREWW',
            'g44': 'WExxFSQUAREWE',
            'f11': 'xxTWO',
            'f12': 'xxTWO',
            'f13': 'xxTWO',
            'f24': 'xxTWO',
            'f34': 'xxTWO',
            'f44': 'xxTWO',
            'reward': 'xxESPIONAGE xxESPIONAGE'},
        'Alone in the Dark': {
            'locregion': 'xxEMPIRE',
            'locresource': 'xxMILITARY',
            'g11': 'OSxxFSQUAREOS',
            'g12': 'YYxxFSQUAREYY',
            'g13': 'LLxxFSQUARELL',
            'g24': 'OOxxFSQUAREOO',
            'g34': 'YYxxFSQUAREYY',
            'g44': 'LExxFSQUARELE',
            'reward': 'xxESPIONAGE xxESPIONAGE'},
        }
    }

original_stdout = sys.stdout

with open ("D:\\Dropbox\\Ziapelta Games\\Git\\six-winters\\csv\\achievement-cards.csv", "w") as csvfile:

    sys.stdout = csvfile

    # Print csv header
    for i in range(len(columns) -1):
        print(columns[i], ',', end='', sep='')
    print(columns[-1])
    
    print()
    
    # Print rows
    for next_stage in card_dict.keys():
        for next_name in card_dict[next_stage].keys():
            for next_col in columns:
                if next_col == 'stage':
                    print('"', next_stage, '",', end='', sep='')
                elif next_col =='name':
                    print('"', next_name, '",', end='', sep='')
                elif next_col == 'star':
                    print('"xxSTAR",', end='', sep='')
                else:
                    if next_col in card_dict[next_stage][next_name].keys():
                        print('"', card_dict[next_stage][next_name][next_col], '",', end='', sep='')
                    else:
                        print('""', ',', end='', sep='')
            print()
        print()
        
    sys.stdout = original_stdout